version: '3.7'

service:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplekey1234
      - ALLOWED_HOSTS=127.0.0.1,localhost

  proxy:
    build:
      context: ./proxy
    volumes:
      -static_data:/vol/static
    ports:
       -"8000:8000"
    depends_on:
       -app


volumes: 
  static_data: